### ISSUE TITLE
Issues getting mqttbridge reporting status and turning monitor on and off

### ISSUE THREAD

**Issue by karldonteljames** [Tom-Hirschberger/MMM-MQTTbridge#29]
I used this for a while a few months back, after an issue my mirror I never got around to looking into why this module stopped working. I think it might be some kind breaking change due to a new version, but couldn't be 100%. 
The only function I need is to be able to turn the monitor on and off via an MQTT home assistant switch. 
I can see that Home Assistant is publishing MQTT commands (monitoring via MQTT Explorer), but the MagicMirror does not seem to be reporting any status. or turning the mirror on or off. - 
Is there a log file I can look into to see if it connecting to the broker?
Is my configuration very wrong?
I would really appreciate some help getting this functionality back.

Thanks In advance

I had this working previously with the following settings:
mqttDictionary.js
```
var mqttHook = [
    {
      mqttTopic: 'cmnd/magicmirror/diningroom/monitor',
      mqttPayload: [
        {
          payloadValue: 'false',
          mqttNotiCmd: ['MONITOROFF']
        },
        {
          payloadValue: 'true',
          mqttNotiCmd: ['MONITORON']
        },
        {
          payloadValue: 'UNDIM',
          mqttNotiCmd: ['UNDIM']
        },
        {
          payloadValue: 'DIM',
          mqttNotiCmd: ['DIM']
        },
      ],
    },
  ];

var mqttNotiCommands = [
    {
      commandId: 'MONITOROFF',
      notiID: 'REMOTE_ACTION',
      notiPayload: {action: 'MONITOROFF'}
    },
    {
      commandId: 'MONITORON',
      notiID: 'REMOTE_ACTION',
      notiPayload: {action: 'MONITORON'}
    },
    {
      commandId: 'DIM',
      notiID: 'REMOTE_ACTION',
      notiPayload: {action: 'BRIGHTNESS', value: '20'}
    },
    {
      commandId: 'UNDIM',
      notiID: 'REMOTE_ACTION',
      notiPayload: {action: 'BRIGHTNESS', value: '255'}
    },
  ];

module.exports = { mqttHook,  mqttNotiCommands}
```
notiDictionary:
```
var notiHook = [
  {
    notiId: "USER_PRESENCE",
    notiPayload: [
      {
        payloadValue: 1,
        notiMqttCmd: ['MONITORON']
      },
      {
        payloadValue: 0,
        notiMqttCmd: ['MONITOROFF']
      }
    ]
  }
];
var notiMqttCommands = [
  {
    commandId: 'MONITOROFF',
    mqttTopic: 'stat/magicmirror/diningroom/monitor',
    mqttMsgPayload: 'MONITOROFF'
  },
  {
    commandId: 'MONITORON',
    mqttTopic: 'stat/magicmirror/diningroom/monitor',
    mqttMsgPayload: 'MONITORON'
  }
];

module.exports = { notiHook, notiMqttCommands };
```
MQTT Switch in Home Assistant:
```
  - platform: mqtt
    name: "MagicMirror"
    command_topic: "cmnd/magicmirror/diningroom/monitor"
    state_topic: "stat/magicmirror/diningroom/monitor"
    payload_on: 'true'
    payload_off: 'false'
    qos: 1
    retain: true
```
config.js
```
               {
                         module: 'MMM-MQTTbridge',
                         disabled: false,
                         config: {
                                  mqttServer: "mqtt://USERNAME:PASSWORD@192.168.12.201:1883",
                                  mqttConfig: {
                                           listenMqtt: true,
                                           interval: 300000,
                                  },
                                  notiConfig: {
                                           listenNoti: true,
                                           ignoreNotiId: ["CLOCK_MINUTE", "NEWS_FEED"],
                                           ignoreNotiSender: ["system", "NEWS_FEED"],
                                  },
                                  // set "NOTIFICATIONS -> MQTT" dictionary at /dict/notiDictionary.js
                                  // set "MQTT -> NOTIFICATIONS" dictionary at /dict/mqttDictionary.js
                                 },
                },
```

![image](https://user-images.githubusercontent.com/25663177/208891749-4beb8225-9c0b-4d2c-abe0-3bf59113cf1b.png)

**Comment by karldonteljames** [comment]
I can see this in my pm2 log.
```
0|mm     | [21.12.2022 17:32.43.284] [ERROR]
0|mm     | Whoops! There was an uncaught exception...
0|mm     | [21.12.2022 17:32.43.341] [ERROR]
0|mm     | TypeError: Cannot read properties of undefined (reading 'resubscribe')
0|mm     |     at MqttClient.subscribe (/home/pi/MagicMirror/modules/MMM-MQTTbridge/node_modules/mqtt/lib/client.js:701:27)
0|mm     |     at MqttClient.<anonymous> (/home/pi/MagicMirror/modules/MMM-MQTTbridge/node_helper.js:84:22)
0|mm     |     at MqttClient.emit (node:events:525:35)
0|mm     |     at Readable.<anonymous> (/home/pi/MagicMirror/modules/MMM-MQTTbridge/node_modules/mqtt/lib/client.js:1863:14)
0|mm     |     at Readable.emit (node:events:513:28)
0|mm     |     at endReadableNT (/home/pi/MagicMirror/modules/MMM-MQTTbridge/node_modules/readable-stream/lib/_stream_readable.js:1094:12)
0|mm     |     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
0|mm     | [21.12.2022 17:32.43.361] [ERROR]
0|mm     | MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm     | [21.12.2022 17:32.43.369] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm     | [21.12.2022 17:32.43.636] [INFO]
```

**Comment by karldonteljames** [comment]
I've sorted the issue above, and I can see that the MQTTbridge is now receiving the MQTT messages of true and false when I send them via home assistant, but the display is still not turning on or off, or reporting it's state.
```
0|mm     | [MQTT bridge] MQTT message received. Topic: cmnd/magicmirror/diningroom/monitor, message: false
0|mm     | [21.12.2022 18:29.52.566] [LOG]   [MQTT bridge] MQTT -> NOTI issued: REMOTE_ACTION, payload: {"action":"MONITOROFF"}
0|mm     | [21.12.2022 18:29.53.674] [LOG]   [MQTT bridge] MQTT message received. Topic: cmnd/magicmirror/diningroom/monitor, message: false
0|mm     | [21.12.2022 18:29.53.688] [LOG]   [MQTT bridge] MQTT -> NOTI issued: REMOTE_ACTION, payload: {"action":"MONITOROFF"}
0|mm     | [21.12.2022 18:30.00.238] [LOG]
0|mm     | [MQTT bridge] MQTT message received. Topic: cmnd/magicmirror/diningroom/monitor, message: true
0|mm     | [21.12.2022 18:30.00.264] [LOG]
0|mm     | [MQTT bridge] MQTT -> NOTI issued: REMOTE_ACTION, payload: {"action":"MONITORON"}
```

**Comment by karldonteljames** [comment]
I didnt realise that i had disabled remote control, after enabling this, the display is now turning on and off as expected, and is reporting it's state correctly back to home assistant.
