### ISSUE TITLE
Cannot read properties of undefined (reading 'resubscribe')

### ISSUE THREAD

**Issue by Michdo93** [Tom-Hirschberger/MMM-MQTTbridge#35]
Hi,

If I try to start MagicMirror I receive following error:

```
[09.02.2023 14:27.00.805] [LOG]   [MQTT bridge] MQTT brocker uses unencrypted connection.
[09.02.2023 14:27.00.826] [ERROR] Whoops! There was an uncaught exception...
[09.02.2023 14:27.00.827] [ERROR] TypeError: Cannot read properties of undefined (reading 'resubscribe')
    at MqttClient.subscribe (/home/mirror/MagicMirror/modules/MMM-MQTTbridge/node_modules/mqtt/lib/client.js:701:27)
    at Class.connectMqtt (/home/mirror/MagicMirror/modules/MMM-MQTTbridge/node_helper.js:80:18)
    at Class.socketNotificationReceived (/home/mirror/MagicMirror/modules/MMM-MQTTbridge/node_helper.js:91:14)
    at Socket.<anonymous> (/home/mirror/MagicMirror/js/node_helper.js:109:11)
    at Socket.emit (node:events:390:28)
    at Socket.emitUntyped (/home/mirror/MagicMirror/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/mirror/MagicMirror/node_modules/socket.io/dist/socket.js:466:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[09.02.2023 14:27.00.828] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[09.02.2023 14:27.00.828] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
```

Thanks in advance.

**Comment by Tom-Hirschberger** [comment]
Hi,

looks like a problem with the configuration to me. Can you share your module configuration of config.js (without username and password) and your dictonary file please?

**Comment by Michdo93** [comment]
Hi,

I fixed it but I do not know how. I have had several mistakes after stoping and starting the MagicMirror. After I restarted my computer this errors no longer existed. I think he had difficulties with some module in general and that's why there were several errors.

I could still use some help. The notiDictonary publishes nothing. I use onConnectMessages for debugging and they work again. So I am sure that the connection to the broker exists.

Here my notiDictionary.js:
```

var notiHook = [
{
    notiId: "CURRENT_PROFILE",
    notiPayload: [
      {
        payloadValue: 'default',
        notiMqttCmd: ["BAD_HUE_LAMPE1_OFF","BAD_HUE_LAMPE2_OFF","BAD_HUE_LAMPE3_OFF","BAD_HUE_LAMPE4_OFF","BAD_HUE_LAMPE5_OFF","BAD_HUE_LAMPE6_OFF","BAD_HUE_BLOOMLAMPE1_OFF","BAD_HUE_BLOOMLAMPE2_OFF","BAD_OSRAM_LEDSTREIFEN_OFF"]
      },
{payloadValue: 'markus', notiMqttCmd: ['BAD_OSRAM_LEDSTREIFEN_ON','BAD_HUE_BLOOMLAMPE1_ON','BAD_HUE_LAMPE6_ON','BAD_HUE_LAMPE3_ON','BAD_HUE_LAMPE1_ON']},
{payloadValue: 'marvin', notiMqttCmd: ['BAD_OSRAM_LEDSTREIFEN_ON','BAD_HUE_BLOOMLAMPE2_ON','BAD_HUE_BLOOMLAMPE1_ON','BAD_HUE_LAMPE6_ON','BAD_HUE_LAMPE5_ON','BAD_HUE_LAMPE2_ON','BAD_HUE_LAMPE1_ON']},
{payloadValue: 'dominik', notiMqttCmd: ['BAD_OSRAM_LEDSTREIFEN_ON','BAD_HUE_BLOOMLAMPE2_ON','BAD_HUE_BLOOMLAMPE1_ON','BAD_HUE_LAMPE6_ON','BAD_HUE_LAMPE5_ON','BAD_HUE_LAMPE4_ON','BAD_HUE_LAMPE3_ON','BAD_HUE_LAMPE2_ON','BAD_HUE_LAMPE1_ON']},
{payloadValue: 'tobias', notiMqttCmd: ['BAD_OSRAM_LEDSTREIFEN_ON','BAD_HUE_BLOOMLAMPE2_ON','BAD_HUE_BLOOMLAMPE1_ON','BAD_HUE_LAMPE5_ON','BAD_HUE_LAMPE3_ON','BAD_HUE_LAMPE1_ON']},
{payloadValue: 'louis', notiMqttCmd: ['BAD_HUE_BLOOMLAMPE2_ON','BAD_HUE_BLOOMLAMPE1_ON','BAD_HUE_LAMPE4_ON','BAD_HUE_LAMPE3_ON']},
{payloadValue: 'leon', notiMqttCmd: ['BAD_OSRAM_LEDSTREIFEN_ON','BAD_HUE_BLOOMLAMPE1_ON','BAD_HUE_LAMPE5_ON','BAD_HUE_LAMPE2_ON']}, //////
   ],
  },

];
var notiMqttCommands = [
  {
    commandId: "BAD_HUE_LAMPE1_ON",
    mqttTopic: "/messages/commands/iBad_Hue_Lampe1_Schalter",
    mqttMsgPayload: 'ON',
  },
  {
    commandId: "BAD_HUE_LAMPE1_OFF",
    mqttTopic: "/messages/commands/iBad_Hue_Lampe1_Schalter",
    mqttMsgPayload: 'OFF',
  },
  {
    commandId: "BAD_HUE_LAMPE2_ON",
    mqttTopic: "/messages/commands/iBad_Hue_Lampe2_Schalter",
    mqttMsgPayload: 'ON'
  },
  {
    commandId: "BAD_HUE_LAMPE2_OFF",
    mqttTopic: "/messages/commands/iBad_Hue_Lampe2_Schalter",
    mqttMsgPayload: 'OFF'
  },
   {
    commandId: "BAD_HUE_LAMPE3_ON",
    mqttTopic: "/messages/commands/iBad_Hue_Lampe3_Schalter",
    mqttMsgPayload: 'ON'
  },
  {
    commandId: "BAD_HUE_LAMPE3_OFF",
    mqttTopic: "/messages/commands/iBad_Hue_Lampe3_Schalter",
    mqttMsgPayload: 'OFF'
  },
   {
    commandId: "BAD_HUE_LAMPE4_ON",
    mqttTopic: "/messages/commands/iBad_Hue_Lampe4_Schalter",
    mqttMsgPayload: 'ON'
  },
  {
    commandId: "BAD_HUE_LAMPE4_OFF",
    mqttTopic: "/messages/commands/iBad_Hue_Lampe4_Schalter",
    mqttMsgPayload: 'OFF'
  },
   {
    commandId: "BAD_HUE_LAMPE5_ON",
    mqttTopic: "/messages/commands/iBad_Hue_Lampe5_Schalter",
    mqttMsgPayload: 'ON'
  },
  {
    commandId: "BAD_HUE_LAMPE5_OFF",
    mqttTopic: "/messages/commands/iBad_Hue_Lampe5_Schalter",
    mqttMsgPayload: 'OFF'
  },
   {
    commandId: "BAD_HUE_LAMPE6_ON",
    mqttTopic: "/messages/commands/iBad_Hue_Lampe6_Schalter",
    mqttMsgPayload: 'ON'
  },
  {
    commandId: "BAD_HUE_LAMPE6_OFF",
    mqttTopic: "/messages/commands/iBad_Hue_Lampe6_Schalter",
    mqttMsgPayload: 'OFF'
  },
  {
    commandId: "BAD_HUE_BLOOMLAMPE1_ON",
    mqttTopic: "/messages/commands/iBad_Hue_BloomLampe1_Schalter",
    mqttMsgPayload: 'ON'
  },
  {
    commandId: "BAD_HUE_BLOOMLAMPE1_OFF",
    mqttTopic: "/messages/commands/iBad_Hue_BloomLampe1_Schalter",
    mqttMsgPayload: 'OFF'
  },
  {
    commandId: "BAD_HUE_BLOOMLAMPE2_ON",
    mqttTopic: "/messages/commands/iBad_Hue_BloomLampe2_Schalter",
    mqttMsgPayload: 'ON'
  },
  {
    commandId: "BAD_HUE_BLOOMLAMPE2_OFF",
    mqttTopic: "/messages/commands/iBad_Hue_BloomLampe2_Schalter",
    mqttMsgPayload: 'OFF'
  },
  {
    commandId: "BAD_OSRAM_LEDSTREIFEN_OFF",
    mqttTopic: "/messages/commands/iBad_Osram_LEDStreifen_Schalter",
    mqttMsgPayload: 'OFF'
  },
  {
    commandId: "BAD_OSRAM_LEDSTREIFEN_ON",
    mqttTopic: "/messages/commands/iBad_Osram_LEDStreifen_Schalter",
    mqttMsgPayload: 'ON'
  },
];

module.exports = { notiHook, notiMqttCommands };
```

And here is my config:

```
{
    module: 'MMM-MQTTbridge',
    disabled: false,
    config: {
     mqttServer: "tcp://:@192.168.0.5:1883",
     mqttConfig:
     {
       listenMqtt: true,
       interval: 30000,
       rejectUnauthorized: true,
       onConnectMessages: [
         {
           topic: "magicmirror/connected",
           msg: "true",
           options: {
             retain: false,
             qos: 0
           }
         },
         {
           topic: "magicmirror/status",
           msg: {value: "online"}
         }
       ]
        },
        notiConfig:
        {
          listenNoti: true,
          ignoreNotiId: ["CLOCK_MINUTE", "NEWS_FEED"],
          ignoreNotiSender: ["system", "NEWS_FEED"],
        },
    },
   },
```

In the logs I can see following:

```
[13.02.2023 14:01.34.355] [LOG]   [MQTT bridge] NOTI->MQTT. Topic: /messages/commands/iBad_Osram_LEDStreifen_Schalter, payload: "ON"
[13.02.2023 14:01.34.357] [LOG]   [MQTT bridge] NOTI->MQTT. Topic: /messages/commands/iBad_Hue_BloomLampe2_Schalter, payload: "ON"
[13.02.2023 14:01.34.358] [LOG]   [MQTT bridge] NOTI->MQTT. Topic: /messages/commands/iBad_Hue_BloomLampe1_Schalter, payload: "ON"
[13.02.2023 14:01.34.358] [LOG]   [MQTT bridge] NOTI->MQTT. Topic: /messages/commands/iBad_Hue_Lampe6_Schalter, payload: "ON"
[13.02.2023 14:01.34.359] [LOG]   [MQTT bridge] NOTI->MQTT. Topic: /messages/commands/iBad_Hue_Lampe5_Schalter, payload: "ON"
[13.02.2023 14:01.34.359] [LOG]   [MQTT bridge] NOTI->MQTT. Topic: /messages/commands/iBad_Hue_Lampe4_Schalter, payload: "ON"
[13.02.2023 14:01.34.360] [LOG]   [MQTT bridge] NOTI->MQTT. Topic: /messages/commands/iBad_Hue_Lampe3_Schalter, payload: "ON"
[13.02.2023 14:01.34.360] [LOG]   [MQTT bridge] NOTI->MQTT. Topic: /messages/commands/iBad_Hue_Lampe2_Schalter, payload: "ON"
[13.02.2023 14:01.34.361] [LOG]   [MQTT bridge] NOTI->MQTT. Topic: /messages/commands/iBad_Hue_Lampe1_Schalter, payload: "ON"
```

But it is never published to this topics. Only the onConnectMessages will work.

**Comment by Tom-Hirschberger** [comment]
Hi,

great to hear that the module works now.
I think the problem ist the starting slashes in your topic configuration. 

Usually 

`mqttTopic: "/messages/... `

should be

`mqttTopic: "messages/...`

You do not use them in the `onConnectMessages` that's why they are working I think.

But I can not test the next days as I only have my mobile

**Comment by Michdo93** [comment]
I have found the problem. The topics are correct. Whoever started here with / one level higher. My problem is the payloads. I may get an ON, but I get an "ON" for example. Means your module is working.

**Comment by Tom-Hirschberger** [comment]
Sounds like a problem i had some time ago.
You may want to give a try to the `stringifyPayload` option. The Default value is `true` which may cause the `"`.
You can set it to `false` either in the `config` section of the module or for each message like in the example

```
  {
    commandId: "Command 3",
    mqttTopic: "shellies/plug/relay/0/command",
    stringifyPayload: false,
    mqttMsgPayload: 'toogle'
  },
```

**Comment by Michdo93** [comment]
I have already done this and it worked. I am not completely stupid :D Thank you.

**Comment by Tom-Hirschberger** [comment]
Sorry, did not want to say that you are stupid.
Great to see it is working now.
I will close the ticket then
